Repository tiffsoa/-Code_Monkies-SOEN341_Project_F24-, pull requests merged in 2024-10, with the labels that each got.

#59 Created a function that processes CSV files for group creation
  SOEN341_Project/SOEN341_Project/urls.py
  SOEN341_Project/mainApp/views.py
Labels: enhancement

#62 60 add create group page for instructors
  SOEN341_Project/mainApp/static/mainApp/css/create_group.css
  SOEN341_Project/mainApp/templates/mainApp/createGroup.html
  SOEN341_Project/mainApp/urls.py
  SOEN341_Project/mainApp/views.py
  SOEN341_Project/manage.py
Labels: enhancement

#65 changed git
  SOEN341_Project/manage.py
Labels: bug

#67 Added "create group" button
  SOEN341_Project/db.sqlite3
  SOEN341_Project/mainApp/static/mainApp/css/instructor_home.css
  SOEN341_Project/mainApp/templates/mainApp/homepageinstructor.html
Labels: enhancement

#69 Style was changed
  SOEN341_Project/mainApp/static/mainApp/css/create_group.css
Labels: enhancement

#73 Modified create group button
  SOEN341_Project/db.sqlite3
  SOEN341_Project/mainApp/static/mainApp/css/instructor_home.css
  SOEN341_Project/mainApp/templates/mainApp/homepageinstructor.html
Labels: enhancement

#75 Redirect now works + better error messages
  SOEN341_Project/mainApp/views.py
Labels: bug

#76 Seperated csv form and manual form
  SOEN341_Project/db.sqlite3
  SOEN341_Project/mainApp/static/mainApp/css/create_group.css
  SOEN341_Project/mainApp/templates/mainApp/createGroup.html
Labels: bug, enhancement

#80 Minor design changes modified
  SOEN341_Project/mainApp/static/mainApp/css/create_group.css
  SOEN341_Project/mainApp/templates/mainApp/createGroup.html
Labels: enhancement

#82 Minor changes made
  SOEN341_Project/mainApp/static/mainApp/css/instructor_home.css
  SOEN341_Project/mainApp/templates/mainApp/homepageinstructor.html
Labels: enhancement

#83 Fix CSV uploading
  SOEN341_Project/mainApp/__pycache__/urls.cpython-312.pyc
  SOEN341_Project/mainApp/__pycache__/views.cpython-312.pyc
  SOEN341_Project/mainApp/templates/mainApp/createGroup.html
  SOEN341_Project/mainApp/views.py
Labels: bug
