Repository tiffsoa/-Code_Monkies-SOEN341_Project_F24-, pull requests merged in 2024-11, with the labels that each got.

#89 Removed all mentions of open/closed groups
  SOEN341_Project/db.sqlite3
  SOEN341_Project/mainApp/__pycache__/models.cpython-312.pyc
  SOEN341_Project/mainApp/__pycache__/urls.cpython-312.pyc
  SOEN341_Project/mainApp/__pycache__/views.cpython-312.pyc
  SOEN341_Project/mainApp/migrations/0008_remove_projects_open_and_more.py
  SOEN341_Project/mainApp/models.py
  SOEN341_Project/mainApp/templates/mainApp/homepageinstructor.html
  SOEN341_Project/mainApp/templates/mainApp/homepagestudent.html
  SOEN341_Project/mainApp/views.py
Labels: enhancement

#91 Made teammembers visible for instructors
  SOEN341_Project/db.sqlite3
  SOEN341_Project/mainApp/__pycache__/models.cpython-312.pyc
  SOEN341_Project/mainApp/__pycache__/urls.cpython-312.pyc
  SOEN341_Project/mainApp/__pycache__/views.cpython-312.pyc
  SOEN341_Project/mainApp/migrations/0009_delete_ratings.py
  SOEN341_Project/mainApp/models.py
  SOEN341_Project/mainApp/templates/mainApp/homepageinstructor.html
  SOEN341_Project/mainApp/templates/mainApp/instructors_students_in_team.html
  SOEN341_Project/mainApp/urls.py
  SOEN341_Project/mainApp/views.py
Labels: enhancement

#104 Created basic view function that handles rating logic
  SOEN341_Project/mainApp/views.py
Labels: enhancement

#109 Add Instructor overall ratings' page
  SOEN341_Project/mainApp/static/mainApp/css/instructorOverallRatings.css
  SOEN341_Project/mainApp/static/mainApp/css/student_home.css
  SOEN341_Project/mainApp/static/mainApp/css/viewTeam.css
  SOEN341_Project/mainApp/templates/mainApp/homepageinstructor.html
  SOEN341_Project/mainApp/templates/mainApp/instructorOverallRatings.html
  SOEN341_Project/mainApp/views.py
Labels: enhancement

#114 Added html files for student and instrucotor
  SOEN341_Project/mainApp/static/mainApp/css/instructorRatings.css
  SOEN341_Project/mainApp/static/mainApp/css/studentTeamRatings.css
  SOEN341_Project/mainApp/templates/mainApp/instructorTeamRatings.html
  SOEN341_Project/mainApp/templates/mainApp/studentTeamRatings.html
Labels: enhancement

#113 106 export instructor overall ratings to csv file
  SOEN341_Project/db.sqlite3
  SOEN341_Project/mainApp/templates/mainApp/instructorOverallRatings.html
  SOEN341_Project/mainApp/views.py
Labels: enhancement

#119 118 add ability to delete group and add user to group
  SOEN341_Project/mainApp/__pycache__/urls.cpython-312.pyc
  SOEN341_Project/mainApp/__pycache__/views.cpython-312.pyc
  SOEN341_Project/mainApp/templates/mainApp/homepageinstructor.html
  SOEN341_Project/mainApp/templates/mainApp/instructors_students_in_team.html
  SOEN341_Project/mainApp/urls.py
  SOEN341_Project/mainApp/views.py
Labels: enhancement

#124 Created additional tests
  SOEN341_Project/SOEN341_Project/__pycache__/__init__.cpython-311.pyc
  SOEN341_Project/SOEN341_Project/__pycache__/settings.cpython-311.pyc
  SOEN341_Project/SOEN341_Project/__pycache__/urls.cpython-311.pyc
  SOEN341_Project/instructor/tests.py
  SOEN341_Project/instructor/views.py
  SOEN341_Project/student/tests.py
  SOEN341_Project/userAuth/tests.py
Labels: Acceptance Test

#126 Bugfix for .csv file creation with multiple groups
  SOEN341_Project/instructor/views.py
Labels: bug fix

#127 Adjusted the delete button to be centered
  SOEN341_Project/SOEN341_Project/__pycache__/__init__.cpython-312.pyc
  SOEN341_Project/SOEN341_Project/__pycache__/settings.cpython-312.pyc
  SOEN341_Project/SOEN341_Project/__pycache__/urls.cpython-312.pyc
  SOEN341_Project/SOEN341_Project/__pycache__/wsgi.cpython-312.pyc
  SOEN341_Project/db.sqlite3
  SOEN341_Project/static/css/instructor/viewTeam.css
  SOEN341_Project/templates/instructor/instructorEditTeam.html
Labels: enhancement

#128 Settings page route
  SOEN341_Project/templates/instructor/instructorEditTeam.html
  SOEN341_Project/templates/instructor/instructorOverallRatings.html
  SOEN341_Project/templates/instructor/instructorSettings.html
  SOEN341_Project/templates/instructor/instructorTeamRatings.html
  SOEN341_Project/templates/student/assess.html
  SOEN341_Project/templates/student/studentSettings.html
  SOEN341_Project/templates/student/studentTeamRatings.html
  SOEN341_Project/templates/student/studentsInTeam.html
Labels: enhancement

#129 Settings
  SOEN341_Project/templates/student/studentSettings.html
Labels: enhancement

#133 Added homepage button
  SOEN341_Project/static/css/instructor/viewTeam.css
  SOEN341_Project/templates/instructor/instructorEditTeam.html
Labels: enhancement

#135 Modified styling of frontend
  SOEN341_Project/static/css/instructor/instructorOverallRatings.css
  SOEN341_Project/static/css/instructor/instructor_home.css
  SOEN341_Project/static/css/student/assess.css
  SOEN341_Project/static/css/student/student.viewTeam.css
  SOEN341_Project/static/css/student/studentTeamRatings.css
  SOEN341_Project/static/css/student/student_home.css
  SOEN341_Project/templates/instructor/instructorOverallRatings.html
  SOEN341_Project/templates/instructor/instructorSettings.html
  SOEN341_Project/templates/student/assess.html
  SOEN341_Project/templates/student/studentSettings.html
  SOEN341_Project/templates/student/studentTeamRatings.html
  SOEN341_Project/templates/student/studentsInTeam.html
Labels: bug, enhancement

#137 Bugs were fixed
  SOEN341_Project/static/css/instructor/instructorRatings.css
  SOEN341_Project/templates/instructor/instructorTeamRatings.html
  SOEN341_Project/templates/student/studentSettings.html
Labels: bug

#140 Test cases added
  SOEN341_Project/instructor/tests.py
  SOEN341_Project/student/tests.py
Labels: Acceptance Test
